networks:
  pg_network:

services:
  postgres:
    networks:
      - pg_network
    container_name: postgresDao
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
   
  pgadmin:
    networks:
      - pg_network
    container_name: pgadminDao
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - 81:81
    volumes:
      - pgdata:/var/lib/pgadmin/data

volumes:
  pgdata:
