name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
      - name: Clean up node_modules
        run: |
          rm -rf /home/achraf/newsApi/node_modules
      - name: Deploy and restart server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: production
        run: |
          cd /home/achraf/newsApi
          npm install
          PORT=3000 JWT_SECRET={{secrets.JWT_SECRET }} ENV=production npm run start:prod
