name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Clean up node_modules
        run: |
          rm -rf /home/achraf/newsApi/node_modules
      - name: delete app
        run: |
          pm2 delete codesquare || true
      - name: Deploy and restart server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 3000
          ENV: prod
        run: |
          cd /home/achraf/newsApi
          npm install
          JWT_SECRET=${{ secrets.JWT_SECRET }} PORT=3000 ENV=production npm run start:prod
