name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies

        run: |
          cd /home/achraf/newsApi
          npm ci  # Install dependencies with npm ci for production builds

      - name: Deploy and restart server
        working-directory: newsApi # Sets newsApi as the working directory
        env:
          PORT: 3000
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: production
        run: |
          npm run start:prod
