name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Clean up node_modules
        run: |
          rm -rf /home/achraf/newsApi/node_modules

      - name: Install dependencies
        run: |
          cd /home/achraf/newsApi
          npm ci  # Clean install with npm ci for production builds

      - name: Deploy and restart server
        env:
          PORT: 3000
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: production
        run: |
          cd /home/achraf/newsApi
          npm run start:prod
