name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository 12
        uses: actions/checkout@v2
      - name: Deploy and restart server
        run: |
          cd /home/achraf/newsApi
          npm install
          PORT=3000 JWT_SECRET=${{ secrets.JWT_SECRET }} ENV=production npm run start:prod
