name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Clean up node_modules
        run: |
          rm -rf /home/achraf/newsApi/node_modules
      - name: delete app
        run: |
          pm2 delete codesquare || true
      - name: restart docker container
        env: PG_ADMIN_PORT=${{ secrets.PG_ADMIN_PORT }}
        run: |
          export PG_ADMIN_PORT=$PG_ADMIN_PORT
          docker-compose down || true
          docker-compose up -d
      - name: Deploy and restart server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 80
          ENV: prod
        run: |
          cd /home/achraf/newsApi
          npm install
          npm run start:prod
