name: VM Deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Change to newsApi directory
        working-directory: newsApi
      - name: Install dependencies
        run: |
          cd newsApi
          npm ci  # Prefer npm ci for production builds

      - name: Deploy and restart server
        env:
          PORT: 3000
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: production
        run: |
          cd newsApi
          npm run start:prod
