name: vm deployer
on:
  push:
    branches: [deploy-prod]
jobs:
    deploy:
      runs-on: self-hosted
      steps:
        - name: Deploy and restart server
          run: |
            cd newsApi
            npm i 
            PORT=3000 JWT_SECRET=*sdsd!sdfd12AFB$f ENV=production npm run start:prod
          
